name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - next
    pull_request:
        branches:
            - main
            - next

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 15.x, 16.x, 17.x]

        steps:
            - uses: actions/checkout@v2

            - name: Using Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Installing dependencies
              run: npm ci

            - name: Building module
              run: npm run build

            - name: Running tests
              run: npm test
