name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"

      - name: Installing dependencies...
        run: npm install -D

      - name: Building site...
        run: npm run docs

      - name: Deleting gitignore
        run: rm -rf .gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          allow_empty_commit: true